### ISSUE TITLE
Bug: ValueError 'default' must be a list

### ISSUE THREAD

**Issue by niftycode** [hedyhli/starcli#102]
**Description**

**Python version**: 3.9

**your operating system (and terminal type of needed)**: macOS Terminal

**starcli version**: 2.17.0

**any suggestions to the cause of the problem? (if possible)**

Running starcli (with options `--lang python -L list` raises a value error:

"ValueError: 'default' must be a list when 'multiple' is true."

I think because of:

    @click.option(
    "--topic",
    "-t",
    default="",
    multiple=True,  # <- this value
    help="Search by topic, can be specified multiple times",

**Comment by hedyhli** [comment]
Thanks, I'll have a look into it

**Comment by davised** [comment]
I'm having the same issue. I'm on archlinux with python 3.9.6. I can't run with `starcli -h` to get the options.

**Comment by hedyhli** [comment]
Oopsie forgot to close
