### ISSUE TITLE
Filter with multiple languages

### ISSUE THREAD

**Issue by Blurry1Wang** [hedyhli/starcli#106]
First, the project is very useful! Thanks for creating it! However, it's kinda embarrassing that we can only search on one language once a time.
Can we add multiple language support so that we can search based on various combination of languages? Like python and c++

**Comment by hedyhli** [comment]
Thanks for bringing this up, it would be a nice feature! It can be achieved by specifying multiple languages with `+language:a+language:b` when querying GitHub. We can possibly allow `--lang` to be specified multiple times or with commas: `--lang=python --lang=cpp` or `--lang=python,cpp`.

**Comment by fgsepter** [comment]
Hi! My friend and I think this is a very good start for our contribution to GitHub. Could we work on this? :)
* I understand that I have asked to solve two issues, but we also have two people here. So it should be not that hard. Hope you can assign us the issues, thx!

**Comment by tongjin0521** [comment]
sure

**Comment by larissalages** [comment]
Hello @hedyhli ! Could I work in this issue?

**Comment by fgsepter** [comment]
@hedyhli Hello, I've submitted a pull request to enable filtering with the combination of languages and spoken languages. 
Currently, we are able to use ```-l Python+JavaScript``` and ```-S en+zh```.

**Comment by hedyhli** [comment]
> Hello @hedyhli ! Could I work in this issue?

Hey @larissalages thanks for you interest but I'll let @fgsepter have a go at this first since they asked first 😄

**Comment by Ladeia** [comment]
This work still open? Can I work on this?

**Comment by vaibhavb** [comment]
Do you still need help? I can pick it up

**Comment by hedyhli** [comment]
Closing as implemented (#116).
