### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by yashksaini-coder** [hedyhli/starcli#130]
I installed starcli and ran the `starcli` expecting to get the help options page. Instead it gave me this error.

![image](https://github.com/user-attachments/assets/b3c72996-6982-4056-a6e1-f644be659c4f)

**Comment by hedyhli** [comment]
Hi, the fix for this issue had been made but it turns out it was unreleased. The release that includes the fix should be published now.

**Comment by yashksaini-coder** [comment]
okh Thx for the update @hedyhli
